### PR TITLE
Fixes downcasting for FinderCommand classes

### LINKED ISSUE #110: Fix up the 3 FinderCommand classes for downcasting

### PR DESCRIPTION
**Pull request by wraineflores**
Request for review
Removed all unnecessary methods & abstract methods
Closes #110

### CODE REVIEW

File: src/main/java/seedu/duke/assets/DoctorList.java [hunk 1]
```diff
@@ -127,38 +127,66 @@ public String toString() {
...
     }
 
     public void findByName(String[] parameterArray) {
-        this.returnedFinderArray = DoctorFinder.findDoctorByName(doctors, parameterArray[1]);
-        createArrayOfFoundDoctors();
+        try {
+            this.returnedFinderArray = DoctorFinder.findDoctorByName(doctors, parameterArray[1]);
+            createArrayOfFoundDoctors();
+        } catch (NullPointerException e) {
+            UI.printParagraph("Doctor doesn't exist please try again!");
```
Comment (Anvitha-r) [inline src/main/java/seedu/duke/assets/DoctorList.java]: maybe can customize the exception to return specific error eg. Doctor with given name doesnt exist

**Review by Anvitha-r — APPROVED** [review]

**Review by tanweili — COMMENTED** [review]
Not sure about what to look out here sorry. If Anvitha or Sharif okay then I think good to go

File: src/main/java/seedu/duke/assets/DoctorList.java (hunk 1 above)
Comment (wraineflores) [reply src/main/java/seedu/duke/assets/DoctorList.java]: Alrighty!
