### PR TITLE
Exception and validator abstraction

### LINKED ISSUE #39: Add exceptions to relevant code for adding and deleting patient
To make this portion of the code more defensive.

### PR DESCRIPTION
**Pull request by kktai1512**
Abstracted validator from parser

Created exception class to handle null errors 

Few issues for the next guy:
Admission date in patient is redundant (therefore, validation part needs to be fixed too)
Logic of view medicine needs to be fixed 

#39 #68

### CODE REVIEW

File: src/test/java/seedu/duke/helper/ParserTest.java [hunk 1]
```diff
@@ -25,20 +26,20 @@ void printDetails(TestInfo testInfo) {
...
         String[] userInputArray = {"paracetamol", "500", "2023-02-02", "Headaches", "500"};
         String userInput = "paracetamol,500,2023-02-02,Headaches,500";
-        assertEquals(true, Parser.validateMedicine(userInputArray));
+        assertTrue(Validator.validateMedicine(userInputArray));
     }
 
     @Test
     @DisplayName("parseAddMedicine method in Parser Class")
-    void parseAddMedicineTest() {
+    void parseAddMedicineTest() throws HalpmiException {
```
Comment (shxr3f) [inline src/test/java/seedu/duke/helper/ParserTest.java:34]: Why does your test method throw an exception? When is it thrown? Because i don't see any exception being thrown?

File: src/main/java/seedu/duke/helper/Command.java [hunk 2]
```diff
@@ -22,143 +23,96 @@ public void viewPatient(PatientList patientList, String nric) {
...
-        if (addAppointmentParameters == null) {
-            ui.printAddAppointmentExampleMessage();
-        } else {
+        try {
+            String[] addAppointmentParameters = Parser.parseAddAppointment(parameters);
             appointmentList.add(addAppointmentParameters);
             UI.printParagraph("The above appointment has been added.");
+        } catch (HalpmiException e) {
+            UI.printParagraph(e.toString());
+            ui.printAddAppointmentExampleMessage();
```
Comment (wraineflores) [inline src/main/java/seedu/duke/helper/Command.java:115]: Shouldn't it be ui instead of UI? Or is there no difference?

**Comment by shxr3f** [comment]
Looks fine!

**Review by wraineflores — APPROVED** [review]
Looks good!

File: src/main/java/seedu/duke/helper/Command.java (hunk 2 above)
Comment (kktai1512) [reply src/main/java/seedu/duke/helper/Command.java:115]: the print paragraph is a static method sooo i just used UI. i think actually moving on we can j change all ui into static methods maybe! tbd
